fint:
  application-id: fint-kontroll-resource-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/kontroll/user
  kontroll:
    resource-catalog:
      pagesize: 50
      source: gui
    opa:
      url: http://fint-kontroll-opa:8181/v1/data/accessmanagement
    authorization:
      authorized-role: https://role-catalog.vigoiks.no/vigo/kontroll/user
      authorized-org-id: vigo.no
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kafka
      - db
logging:
  level:
    root: INFO
    org.apache.kafka: WARN

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
