fint:
  org-id: fintlabs.no
  kafka:
    default-replicas: 1
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
  kontroll:
    resource-catalog:
      pagesize: 50
      source: fint
    opa:
      url: http://localhost:8181/v1/data/accessmanagement
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
#    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: __init.sql
              create-source: metadata
    hibernate:
      ddl-auto: none
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    hikari:
      schema: resources
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300

server:
  port: 8084

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    net.sf.ehcache: WARN
    no.fintlabs.cache.ehcache: WARN
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


