apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-catalog
  app.kubernetes.io/instance: fint-kontroll-resource-catalog_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "https://role-catalog.vigoiks.no/vigo/kontroll/user"
      - op: replace
        path: "/spec/env/1/value"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/2/value"
        value: "fint-kontroll-resource-catalog"
      - op: replace
        path: "/spec/env/3/value"
        value: "-XX:+ExitOnOutOfMemoryError -Xmx1950m"
      - op: replace
        path: "/spec/env/4/value"
        value: "fint"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/fintlabs-no/api/resources"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/fintlabs-no"
    target:
      kind: Application
      name: fint-kontroll-resource-catalog


