CREATE TABLE handhevingstype_kodeverk (
    id BIGINT generated by default as identity PRIMARY KEY,
    fk_label VARCHAR(255) NOT NULL,
    label VARCHAR(255) NOT NULL
);

INSERT INTO handhevingstype_kodeverk (fk_label, label) VALUES ('Maks antall', 'HARDSTOP');
INSERT INTO handhevingstype_kodeverk (fk_label, label) VALUES ('Kan overskrides', 'FLOATING');
INSERT INTO handhevingstype_kodeverk (fk_label, label) VALUES ('Fri for alle', 'FREE_ALL');
INSERT INTO handhevingstype_kodeverk (fk_label, label) VALUES ('Fri for elever', 'FREE_STUDENT');
INSERT INTO handhevingstype_kodeverk (fk_label, label) VALUES ('Fri for utdanning', 'FREE_EDU');

