create table application_resource
(
    id                           bigint generated by default as identity
        primary key,
    resource_id                  varchar(255),
    resource_name                varchar(255),
    resource_type                varchar(255),
    access_type                  varchar(255),
    application_access_role      varchar(255),
    application_access_type      varchar(255),
    resource_limit               bigint,
    resource_owner_org_unit_id   varchar(255),
    resource_owner_org_unit_name varchar(255)
);

create table application_resource_location
(
    id             bigint generated by default as identity
        primary key,
    org_unit_name  varchar(255),
    orgunit_id     varchar(255),
    resource_id    varchar(255),
    resource_limit bigint
);

create table application_resource_platform
(
    id       bigint not null
        constraint fk65hwdpt5pfioanqbjw94g88qx
            references application_resource,
    platform varchar(255)
);

create table application_resource_valid_for_org_units
(
    application_resource_id bigint not null
        constraint fk5xu4y1oug35mkm2x7q70b9pet
            references application_resource,
    valid_for_org_units_id  bigint not null
        constraint uk_70eq9s89y72lu9fkxw5g4qak3
            unique
        constraint fkf5c29k5i7vgjl2ds4moekvgle
            references application_resource_location
);

create table application_resource_valid_for_roles
(
    id              bigint not null
        constraint fk5c86mybjdkjvmkixg8s9u1cnw
            references application_resource,
    valid_for_roles varchar(255)
);