create table resource_availability
(
    id                           bigint generated by default as identity
        primary key,
    resource_id                  varchar(255),
    assigned_resources           bigint
);

create table resource_consumer_assignments
(
    id              bigint generated by default as identity
        primary key,
    orgunit_id           varchar(255),
    assigned_resources   bigint

);


create table resource_availability_resource_consumer_assignments
(
    resource_availability_id bigint not null
constraint abc
references resource_availability,
    resource_consumer_assignments_id bigint not null
constraint def
unique
constraint ghj
references resource_consumer_assignments

)




