alter table application_resource ADD COLUMN need_approval boolean NOT NULL DEFAULT false;

CREATE TABLE brukertype_kodeverk (
    id BIGINT generated by default as identity PRIMARY KEY,
    fk_label VARCHAR(255) NOT NULL,
    label VARCHAR(255) NOT NULL
);



