apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-resource-catalog
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-resource-catalog:latest
  imagePullPolicy: Always
  url:
    hostname: kontroll.vigoiks.no
    basePath: /beta/fintlabs-no
  ingress:
    enabled: true
    basePath: /beta/fintlabs-no/api/resources
    middlewares:
      - fint-kontroll-sso
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
  database:
    database: fint-kontroll
  env:
    - name: fint.kontroll.authorization.authorized-role
      value: "https://role-catalog.vigoiks.no/vigo/kontroll/user"
    - name: fint.kontroll.authorization.authorized-org-id
      value: "vigo.no"
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-resource-catalog'
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:+ExitOnOutOfMemoryError -Xmx1950m"
    - name: fint.kontroll.resource-catalog.source
      value: gui
  envFrom:
    - configMapRef:
        name: fint-kontroll-access-management-config
